In [40]:
import os
os.makedirs(os.path.join('.','data'), exist_ok=True)
os.makedirs(os.path.join('.','data','test'),exist_ok=True)

In [3]:
data_file='./data/house_tiny.csv'

In [8]:
with open(data_file, 'w') as f:
    f.write('NumRooms, Alley, Price\n') #列title
    f.write('NA,Pave,127500\n')  # 每行表示一个数据样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')
    f.write('6,SB,267000\n')

In [9]:
import pandas as pd
data=pd.read_csv(data_file)
data

   NumRooms  Alley   Price
0       NaN   Pave  127500
1       2.0    NaN  106000
2       4.0    NaN  178100
3       NaN    NaN  140000
4       6.0     SB  267000

In [35]:
inputs, output = data.iloc[:,0:2], data.iloc[:,-1]
print(inputs), print(output)
inputs

   NumRooms  Alley
0       NaN   Pave
1       2.0    NaN
2       4.0    NaN
3       NaN    NaN
4       6.0     SB
0    127500
1    106000
2    178100
3    140000
4    267000
Name:  Price, dtype: int64

   NumRooms  Alley
0       NaN   Pave
1       2.0    NaN
2       4.0    NaN
3       NaN    NaN
4       6.0     SB

In [36]:
inputs = inputs.fillna(inputs.mean(numeric_only=True))
inputs

   NumRooms  Alley
0       4.0   Pave
1       2.0    NaN
2       4.0    NaN
3       4.0    NaN
4       6.0     SB

In [37]:
inputs = pd.get_dummies(inputs, dummy_na=True, dtype=int)
inputs  # 进行是否的判断

   NumRooms   Alley_Pave   Alley_SB   Alley_nan
0       4.0            1          0           0
1       2.0            0          0           1
2       4.0            0          0           1
3       4.0            0          0           1
4       6.0            0          1           0

In [39]:
import torch
x,y =torch.tensor(inputs.values), torch.tensor(output.values)
x,y
# 这样就转换成为了一个特征对应一个结果，就可以用于学习模型

(tensor([[4., 1., 0., 0.],
         [2., 0., 0., 1.],
         [4., 0., 0., 1.],
         [4., 0., 0., 1.],
         [6., 0., 1., 0.]], dtype=torch.float64),
 tensor([127500, 106000, 178100, 140000, 267000]))

In [49]:
a=torch.arange(12)
b=a.reshape((3,4))

In [50]:
a,b

(tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]))

In [52]:
b[:]=2
a,b  # reshape不会申请新的地址，如果b是a reshape而来，那么b的改变会导致a的改变

(tensor([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]),
 tensor([[2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2]]))